services:
  flask:
    image: titou4n/titouservice-flask:latest
    container_name: titouservice-flask
    restart: unless-stopped

    environment:
      ENV_PROD: "true"
      FLASK_ENV: "production"

      RATELIMIT_STORAGE_URI: redis://redis:6379/0

    volumes:
      - db-data:/app/Data/db
      - ./secrets:/run/secrets

    expose:
      - "5000"

    depends_on:
      redis:
        condition: service_healthy

    networks:
      - titouservice-network

    secrets:
      - secret_key
      - username_super_admin
      - password_super_admin
      - email_app_password
      - omdb_api_key
      - twelvedata_api_key

  redis:
    image: redis:7-alpine
    container_name: titouservice-redis
    restart: unless-stopped

    command:
      - redis-server
      - --appendonly
      - yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

    volumes:
      - redis-data:/data

    networks:
      - titouservice-network

  nginx:
    image: nginx:latest
    container_name: titouservice-nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/ssl:ro

    depends_on:
      - flask

    networks:
      - titouservice-network

networks:
  titouservice-network:
    driver: bridge

volumes:
  db-data:
  redis-data:

secrets:
  secret_key:
    file: ./secrets/secret_key.txt
  username_super_admin:
    file: ./secrets/username_super_admin.txt
  password_super_admin:
    file: ./secrets/password_super_admin.txt
  email_app_password:
    file: ./secrets/email_app_password.txt
  omdb_api_key:
    file: ./secrets/omdb_api_key.txt
  twelvedata_api_key:
    file: ./secrets/twelvedata_api_key.txt