services:
  flask:
    image: titou4n/titouservice-flask:latest
    container_name: titouservice-flask
    restart: unless-stopped

    ports:
      - "5000:5000"

    volumes:
      - db-data:/app/Data/db
      - ./secrets:/run/secrets

    networks:
      - titouservice-network
    secrets:
      - secret_key
      - email_app_password
      - omdb_api_key
      - twelvedata_api_key

  nginx:
    image: titou4n/titouservice-nginx:latest
    container_name: titouservice-nginx
    restart: unless-stopped

    ports:
      - "8080:80"
      - "8443:443"

    networks:
      - titouservice-network

    depends_on:
      - flask

networks:
  titouservice-network:
    driver: bridge

secrets:
  secret_key:
    file: ./secrets/secret_key.txt
  email_app_password:
    file: ./secrets/email_app_password.txt
  omdb_api_key:
    file: ./secrets/omdb_api_key.txt
  twelvedata_api_key:
    file: ./secrets/twelvedata_api_key.txt

volumes:
  db-data: