services:
  flask:
    image: titou4n/titouservice-flask:latest
    container_name: titouservice-flask
    restart: unless-stopped

    environment:
      ENV_PROD: "true"
      FLASK_ENV: "production"

    volumes:
      - db-data:/app/Data/db
      - ./secrets:/run/secrets

    expose:
      - "5000"

    networks:
      - titouservice-network

    secrets:
      - secret_key
      - username_super_admin
      - password_super_admin
      - email_app_password
      - omdb_api_key
      - twelvedata_api_key


  nginx:
    image: nginx:latest
    container_name: titouservice-nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      # IMPORTANT : conf.d only
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/ssl:ro

    depends_on:
      - flask

    networks:
      - titouservice-network


networks:
  titouservice-network:
    driver: bridge


volumes:
  db-data:


secrets:
  secret_key:
    file: ./secrets/secret_key.txt
  username_super_admin:
    file: ./secrets/username_super_admin.txt
  password_super_admin:
    file: ./secrets/password_super_admin.txt
  email_app_password:
    file: ./secrets/email_app_password.txt
  omdb_api_key:
    file: ./secrets/omdb_api_key.txt
  twelvedata_api_key:
    file: ./secrets/twelvedata_api_key.txt